/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "on-tertiary-container": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "on-surface": "#191c1d",
        "on-background": "#191c1d",
        "on-primary-fixed": "#001a41",
        "primary-container": "#1a73e8",
        "surface": "#f8f9fa",
        "primary-fixed-dim": "#adc7ff",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed-variant": "#005312",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#002204",
        "on-secondary-fixed-variant": "#2e4673",
        "surface-dim": "#d9dadb",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9fa",
        "on-tertiary": "#ffffff",
        "surface-container": "#edeeef",
        "inverse-primary": "#adc7ff",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "secondary": "#475e8c",
        "on-primary-container": "#ffffff",
        "outline-variant": "#c1c6d6",
        "primary": "#005bbf",
        "primary-fixed": "#d8e2ff",
        "outline": "#727785",
        "secondary-fixed-dim": "#afc7fb",
        "tertiary-fixed-dim": "#88d982",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d8e2ff",
        "surface-tint": "#005bc0",
        "surface-variant": "#e1e3e4",
        "surface-container-low": "#f3f4f5",
        "on-surface-variant": "#414754",
        "on-primary-fixed-variant": "#004493",
        "background": "#f8f9fa",
        "secondary-container": "#b2c9fe",
        "on-secondary-fixed": "#001a41",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#1a6c23",
        "on-secondary-container": "#3d5481",
        "on-secondary": "#ffffff",
        "tertiary-container": "#37863a",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#a3f69c"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}